# permissions for end users to edit terraformstates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terraformstate-editor-role
rules:
- apiGroups:
  - terraform.patoarvizu.dev
  resources:
  - terraformstates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terraform.patoarvizu.dev
  resources:
  - terraformstates/status
  verbs:
  - get
