# permissions for end users to view terraformstates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terraformstate-viewer-role
rules:
- apiGroups:
  - terraform.patoarvizu.dev
  resources:
  - terraformstates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - terraform.patoarvizu.dev
  resources:
  - terraformstates/status
  verbs:
  - get
