apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: amphibian
  name: amphibian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amphibian
  template:
    metadata:
      labels:
        app: amphibian
      {{- if .Values.podAnnotations }}
      annotations: {{ toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: amphibian
      initContainers:
      - name: install-terraform
        image: {{ .Values.terraformBinary.initContainerImage }}
        command:
        - sh
        - -c
        - 'wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_${TERRAFORM_OS}_${TERRAFORM_ARCH}.zip && unzip terraform_${TERRAFORM_VERSION}_${TERRAFORM_OS}_${TERRAFORM_ARCH}.zip && cp terraform /terraform-bin/'
        volumeMounts:
        - mountPath: /terraform-bin
          name: terraform-bin
        env:
        - name: TERRAFORM_VERSION
          value: {{ .Values.terraformBinary.version }}
        - name: TERRAFORM_OS
          value: {{ .Values.terraformBinary.operatingSystem }}
        - name: TERRAFORM_ARCH
          value: {{ .Values.terraformBinary.arch }}
      containers:
      - args:
        - --enable-leader-election
        command:
        - /manager
        env:
        - name: TF_CLI_CONFIG_FILE
          value: /terraform/.terraformrc
        - name: WATCH_NAMESPACE
          value: {{ .Values.watchNamespace | quote }}
        {{- if .Values.authEnvVars }}
        {{- toYaml .Values.authEnvVars | nindent 8 }}
        {{- end }}
        image: patoarvizu/amphibian:{{ .Values.imageVersion }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: manager
        resources: {{ toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /terraform
          name: terraform
        - mountPath: /terraform-bin
          name: terraform-bin
        {{- if .Values.volumeMounts }}
        {{- toYaml .Values.volumeMounts | nindent 8 }}
        {{- end }}
        ports:
        - name: http-metrics
          containerPort: 8080
      volumes:
      - emptyDir:
          medium: Memory
        name: terraform
      - emptyDir:
          medium: Memory
        name: terraform-bin
      {{- if .Values.volumes }}
      {{- toYaml .Values.volumes | nindent 6 }}
      {{- end }}
